ValidArgumentsInfo: array of AnsiString =
  ('--InputDir:AnsiString',
   '--TmpDir:AnsiString',
   '--OutputDir:AnsiString',
  '--Debug:Integer', '--Pipeline.FromStepID:Integer', '--Pipeline.StepID:Integer');
ValidArgumentsValues: array of AnsiString =
  ('/home/khabardar/Projects/NLP-Dataset/1BWLM/NLP/1BWLM/repo/',
   '/tmp/1BWLM',
   '/home/khabardar/Projects/NLP-Dataset/1BWLM/NLP/',
   '-1', '1', '-1');
